include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    use_build_context_synchronously: false
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule