name: letbike
description: Cyclist marketplace

publish_to: 'none'

version: 1.0.5+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  permission_handler: ^6.1.1
  flutter_markdown: ^0.6.1
  url_launcher: ^6.0.3
  emojis: ^0.9.3
  carousel_slider: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  multi_image_picker2: ^5.0.02
  firebase_core: ^1.10.5
  google_sign_in: ^5.2.1
  firebase_auth: ^3.3.3
  flutterfire_ui: ^0.2.0+2
  cupertino_icons: ^1.0.4
  google_mobile_ads: ^1.0.1
  
flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/load.gif