name: letbike
description: Cyclist marketplace

publish_to: 'none'

version: 1.0.6+4

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  permission_handler: ^9.2.0
  flutter_markdown: ^0.6.1
  url_launcher: ^6.0.3
  emojis: ^0.9.3
  carousel_slider: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  multi_image_picker2: ^5.0.02
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.2
  google_mobile_ads: ^1.2.0
  
flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/load.gif
    - assets/icon.png